import { observer } from 'mobx-react-lite';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { Pokemon } from '../src/interfaces/pokemon';
import store from '../src/stores/store';
import styles from '../styles/Home.module.css';

const NEXT_PUBLIC_API_URL = 'http://localhost:3000';

export async function getServerSideProps() {
    const response = await fetch(`${NEXT_PUBLIC_API_URL}/api/pokemon`);

    store.pokemons = await response.json();

    return {
        props: {
            initialPokemons: store.pokemons
        }
    };
}

const Home: NextPage = ({
    initialPokemons = []
}: {
    initialPokemons: Array<Pokemon>;
}) => {
    useEffect(() => {
        store.pokemons = initialPokemons;
    }, [initialPokemons]);

    return (
        <div className={styles.main}>
            <Head>
                <title>Pokemons</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div>
                <input
                    type='text'
                    value={store.filter}
                    onChange={(e) => (store.filter = e.target.value)}
                    className={styles.search}
                />
            </div>
            <div className={styles.container}>
                {store.filteredPokemons.slice(0, 20).map((pokemon) => {
                    return (
                        <div key={pokemon.id}>
                            <img
                                alt={pokemon.name}
                                src={pokemon.image}
                                className={styles.image}
                            />
                            <h2>{pokemon.name}</h2>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

export default observer(Home);
