import type { NextPage } from 'next';
import Head from 'next/head';
import { useMemo, useState } from 'react';
import { useQuery } from 'react-query';
import { Pokemon } from '../interfaces/pokemon';
import styles from '../styles/Home.module.css';

const NEXT_PUBLIC_API_URL = 'http://localhost:3000';

const getPokemons = (): Promise<Array<Pokemon>> =>
    fetch(`${NEXT_PUBLIC_API_URL}/api/pokemon`).then((response) => response.json());

export async function getServerSideProps() {
    return {
        props: {
            initialPokemons: await getPokemons()
        }
    };
}

const Home: NextPage = ({
    initialPokemons = []
}: {
    initialPokemons: Array<Pokemon>;
}) => {
    const { data: pokemons } = useQuery('pokemons', getPokemons, {
        initialData: initialPokemons,
        refetchOnMount: false,
        refetchOnWindowFocus: false
    });

    const [filter, setFilter] = useState('');

    const filteredPokemons = useMemo(
        () =>
            pokemons.filter((pokemon) =>
                pokemon.name.toLowerCase().includes(filter.toLowerCase())
            ),
        [pokemons, filter]
    );

    return (
        <div className={styles.main}>
            <Head>
                <title>Pokemons</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div>
                <input
                    type='text'
                    value={filter}
                    onChange={(e) => setFilter(e.target.value)}
                    className={styles.search}
                />
            </div>
            <div className={styles.container}>
                {filteredPokemons.slice(0, 20).map((pokemon) => {
                    return (
                        <div key={pokemon.id}>
                            <img
                                alt={pokemon.name}
                                src={pokemon.image}
                                className={styles.image}
                            />
                            <h2>{pokemon.name}</h2>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

export default Home;
