import type { NextPage } from 'next';
import Head from 'next/head';
import { usePokemon } from '../src/stores/store';
import styles from '../styles/Home.module.css';

export { getServerSideProps } from '../src/stores/store';

const Home: NextPage = () => {
    const { filter, setFilter, pokemons } = usePokemon();

    return (
        <div className={styles.main}>
            <Head>
                <title>Pokemons</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div>
                <input
                    type='text'
                    value={filter}
                    onChange={(e) => setFilter(e.target.value)}
                    className={styles.search}
                />
            </div>
            <div className={styles.container}>
                {pokemons.slice(0, 20).map((pokemon) => {
                    return (
                        <div key={pokemon.id}>
                            <img
                                alt={pokemon.name}
                                src={pokemon.image}
                                className={styles.image}
                            />
                            <h2>{pokemon.name}</h2>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

export default Home;
